Added self-update command.

diff --git a/sscp b/sscp
--- a/sscp
+++ b/sscp
@@ -50,6 +50,12 @@ SSCP_NO_COLOR=${SSCP_NO_COLOR:-0}
 SSCP_VERBOSE=${SSCP_VERBOSE:-${VERBOSE}}
 sscp_verbose=${SSCP_VERBOSE}
 
+if [ "${VERBOSE_DEBUG}" -eq "${SSCP_VERBOSE}" ]; then
+  # enable traced output
+  set -o xtrace
+fi
+
+download_url='https://raw.github.com/rikby/sscp/master/download'
 connect=${connect:-${SSCP_CONNECT}}
 
 if [ '1' == "${SSCP_NO_COLOR}" ]; then
@@ -237,7 +243,7 @@ read_params () {
 
   # Process options
   # validate and redefine options
-  OPTS=`getopt -o gp:hH:csD -l use-vcs,port:,help,host:,create-destination,silent,debug -- "$@"`
+  OPTS=`getopt -o gp:hH:csD -l use-vcs,port:,help,host:,create-destination,verbose,debug -- "$@"`
   eval set -- "${OPTS}"
 
   while true; do
@@ -294,7 +300,7 @@ read_params () {
     esac
   done
 
-  tar_options=$@
+  rest_options=$@
 }
 
 define_exclude_options() {
@@ -311,7 +317,7 @@ define_exclude_options() {
 
 load_config () {
   # Default values
-  tar_options=''
+  rest_options=''
   action_type=''
   path1=''
   path2=''
@@ -416,9 +422,9 @@ deploy_target() {
     put_printf "Packing file/s..."
     rm -f $(basename ${source_path}).tar.gz
     if [ ${upload_type} = 'd' ]; then
-      tar czf $(basename ${source_path}).tar.gz -C ${source_path} . ${exclude} ${tar_options}
+      tar czf $(basename ${source_path}).tar.gz -C ${source_path} . ${exclude} ${rest_options}
     else
-      tar czf $(basename ${source_path}).tar.gz ${source_path} ${exclude} ${tar_options}
+      tar czf $(basename ${source_path}).tar.gz ${source_path} ${exclude} ${rest_options}
     fi
     put_echo "${t_OK}"
 
@@ -468,7 +474,7 @@ download_target() {
     put_printf "Packing file/s..."
     download_file="${SSCP_TEMP}/${target_basename}.tar.gz"
     ${ssh_connect} "rm -f ${download_file}" # clean up
-    ${ssh_connect} "tar cf ${download_file} -C ${target_dir} ${target_to_archive} ${exclude} ${tar_options}"
+    ${ssh_connect} "tar cf ${download_file} -C ${target_dir} ${target_to_archive} ${exclude} ${rest_options}"
     put_echo "${t_OK}"
   fi
 
@@ -488,6 +494,25 @@ download_target() {
   else
     echo 'Archive of target file/s: './${target_basename}.tar.gz
   fi
+}
+
+self_update () {
+  if [ -e ${__file} ] && [ ! -w ${__file} ]; then
+      echo 'error: No permissions to perform update.'
+      exit 1
+  fi
+
+  put_echo ${VERBOSE_VERY} "Downloading by ${download_url}..."
+  put_echo ${VERBOSE_DEBUG} "cmd: curl -Ls ${download_url} | bash -s -- --file ${__file} $@"
+
+  if ! curl -Ls ${download_url} | bash -s -- --file ${__file} $@ > /dev/null 2>&1; then
+    echo 'error: Cannot complete update.'
+    exit 1
+  fi
+
+  # show version
+  ${__file} --help | head -1 | grep -oE '[v].*'
+  echo 'Update completed.'
 }
 
 process_deployment() {
@@ -516,6 +541,9 @@ process_deployment() {
   elif [[ "${action_type}" =~ ^(show-)?ssh-connection$ ]]; then
     echo ${ssh_connect}
     return
+  elif [[ "${action_type}" =~ self-?update ]]; then
+    self_update ${rest_options}
+    exit 0
   elif [[ "${action_type}" =~ ^(show-)?vars$ ]]; then
     cat << EOF
 # default name of config file
